export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
// 
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILS = 'PRODUCT_LIST_FAILS'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILS = 'PRODUCT_DETAILS_FAILS'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_NEW_LOGOUT = 'USER_NEW_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

// 
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START'
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS'
export const GOOGLE_SIGN_IN_FAIL = 'GOOGLE_SIGN_IN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const ADD_TO_BASKET = 'ADD_TO_BASKET'


export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEMS = 'ADD_ITEMS'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const TOGGLW_ITEMS = 'TOGGLW_ITEMS'
export const CLOSE_ITEMS = 'CLOSE_ITEMS'
export const BANNER_ITEMS = 'BANNER_ITEMS'
export const INCREASE_ITEMS = 'INCREASE_ITEMS'
export const DECREASE_ITEMS = 'DECREASE_ITEMS'
export const TOTAL_ITEMS = 'TOTAL_ITEMS'
export const DETAILS_ITEMS = 'DETAILS_ITEMS'

