export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'


export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START'
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS'
export const GOOGLE_SIGN_IN_FAIL = 'GOOGLE_SIGN_IN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const ADD_TO_BASKET = 'ADD_TO_BASKET'


export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEMS = 'ADD_ITEMS'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const TOGGLW_ITEMS = 'TOGGLW_ITEMS'
export const CLOSE_ITEMS = 'CLOSE_ITEMS'
export const BANNER_ITEMS = 'BANNER_ITEMS'
export const INCREASE_ITEMS = 'INCREASE_ITEMS'
export const DECREASE_ITEMS = 'DECREASE_ITEMS'
export const TOTAL_ITEMS = 'TOTAL_ITEMS'
export const DETAILS_ITEMS = 'DETAILS_ITEMS'

